### ISSUE TITLE
new_socketcall should use access_ok

### ISSUE THREAD

**Issue by jpoltr** [sha0coder/LAF#2]
You should use access_ok() before dereferencing user pointers in new_socketcall.

Also TOCTOU issue, but you probably don't care about that...

**Comment by sha0coder** [comment]
new_socketcall() *args fixed, thanks!!

**Comment by sha0coder** [comment]
The TOCTOU I care is the ssh's ;)

**Comment by capitanx** [comment]
Thank you jpoltr :)
Please, can you check the code to verify the sha0 commit and close this issue?

Regards!
